name: Minimum version tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up tox environment
        shell: bash
        run: |
          pver=${{ matrix.python-version }}
          tox_env="-epy${pver/./}"
          echo tox_env
          echo TOX_ENV=$tox_env >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sed -i 's/[>~]=/==/g' requirements-dev.txt requirements.txt
          cat <<- EOF > get_tox_minversion.py
          import configparser
          config = configparser.ConfigParser()
          config.read("tox.ini")
          print(config["tox"]["minversion"])
          EOF
          pip install tox==$(python3 get_tox_minversion.py)
      - name: Test using tox environment
        run: |
          tox ${{ env.TOX_ENV }}
